export const APPROVE_PRODUCT = "APPROVE_PRODUCT";
export const CONFIRM_PRODUCT = "CONFIRM_PRODUCT";
export const MARK_MISSING = "MARK_MISSING";
export const MARK_URGENT_MISSING = "MARK_URGENT_MISSING";
export const FETCH_PRODUCTS_SUCCESS = "FETCH_PRODUCTS_SUCCESS";
